### ISSUE TITLE
Console Question

### ISSUE THREAD

**Issue by bbetter** [foobnix/foobnix#103]
is there any terminal command to show full info about song now-playing?

**Comment by zavlab1** [comment]
Yes.
foobnix --now-playing

There are many parameters yet.
"--next", "--prev", "--stop", "--pause", "--play", "--volume-up", "--volume-down", "--mute", "--show-hide", "--show", "--hide", "--play-pause", "--download", "--version", "--state".

Now I have checked the work of so commands and I saw that there is unwanted string "/usr/bin/xsel" in output. I fix this and made commit in my branch. You need update from my branch (zavlab1) to 	make away with extra string.

**Comment by andriypuhach** [comment]
yes, there is one extra string, had to omit it in my conky configuration with sed command
one more question is, there any possibility to subscribe to changing of this command result,
now i'm just trying to execute it once per second, to update my current playing song. in case i change it, or ends up, and next is started.

**Comment by zavlab1** [comment]
Until now, this was not possible. But today I realized it and to commit to my branch.
I added signal "current". Your application can subscribe to it via dbus-monitor. For example:
`dbus-monitor --session "sender=org.mpris.MediaPlayer2.foobnix, path=/Player, member=current"`
And on every change of song you will get so output:
`signal sender =: 1.159 -> dest = (null destination) serial = 42 path = / Player; interface = org.freedesktop.MediaPlayer; member = track_changed`
`   string "Yohanna - Butterflies and Elvis" `
`   string "FLAC | Ch: 2 | 16 bit | 44100Hz | 918 kbps | 04:51 | 31.87 MB" `

**Comment by andriypuhach** [comment]
great, thx for quick replies and fixes.

**Comment by zavlab1** [comment]
Да не за что!

**Comment by zavlab1** [comment]
На всякий случай - надеюсь поможет:

Example of script for listening "current" signal.

`#!/usr/bin/env python`

`def my_func(track, info):
        print track, "\n", info`

`import dbus, gobject`
`from dbus.mainloop.glib import DBusGMainLoop`

`    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)`
`    bus = dbus.SessionBus()`

`bus.add_signal_receiver(my_func,
                        dbus_interface="org.freedesktop.MediaPlayer",
                        signal_name="current")`

`loop = gobject.MainLoop()`
`loop.run()`

Output:
`Yohanna - Butterflies and Elvis`
`FLAC | Ch: 2 | 16 bit | 44100Hz | 918 kbps | 04:51 | 31.87 MB`
