### ISSUE TITLE
Улучшение поведения колонок

### ISSUE THREAD

**Issue by sojusnik** [foobnix/foobnix#104]
Здравия разработчикам!

На Ubuntu Gnome 15.04 c Gnome 3.14 и Foobnix 3.1.01 есть проблемы с колонками: 

1. Не изменяется размер колонки, которая отображает длину песни
2. Когда нажимаешь на название колонок, сперва открывается меню, а только потом можно редактировать колонки.
3. Если текст не вмещается в колонку, то это желательно обозначить тремя точками в конце текста, пример см. [здесь](http://i.imgur.com/B8onxR8.png).

[Видео](https://mega.nz/#!zxInAb7b!rtsg1ORTbz59gTyxUNuYV_fiV35yZRE1lf1-ozf_0KQ), наглядно демонстрирующее проблемы (не обращайте внимание на курсор мыши - он в видео зависает на последней форме, но "в реале" работает нормально).

Заранее благодарен!

**Comment by zavlab1** [comment]
На счет первого - надо будет посмотреть на 15.04. Т.к. у меня на 14.04 LTS размер колонки меняется хорошо.
Второе - уже поправлено и закоммичено https://github.com/foobnix/foobnix/issues/96 .
Третье - надо попытаться реализовать.

**Comment by zavlab1** [comment]
Уточняю. Размер колонки времени задан фиксированно, чтобы при изменениях размеров плейлиста время всегда оставалось видимым. Больше размер этой колонки делать тоже нет. Т.е. профит от фиксированного размера выше, чем от плавающего.
По второму пункту уже писал, что баг с меню при редактированию колонок уже закрыт. Так что ждите в следующем релизе.
Округление текста в колонках с помощью многоточия реализовал. Спасибо за хорошую идею!

**Comment by region51** [comment]
Я дико извиняюсь, но где этот коммит https://github.com/foobnix/foobnix/commits/master???

**Comment by POPSuL** [comment]
@region51 https://github.com/zavlab1/foobnix/commit/d7e58e7e4b4cae4c3cca39a93fb2c9dfdc55c57c вот же он

**Comment by region51** [comment]
@POPSuL угу, мой косяк.

**Comment by region51** [comment]
и еще опять эта беда, см столбец № 08 не полностью
![2015-09-23 14-00-15](https://cloud.githubusercontent.com/assets/13280183/10043505/573f0150-61fc-11e5-8344-3078ecb47c75.png)

**Comment by zavlab1** [comment]
Хорошо. Уговорили. Сделал колонки № и Время изменяемыми. Оставил фиксированным только столбец с указателем (он по-любому должен быть всегда виден). Чтобы колонки не терялись, минимальный размер поставил 20px.
