### ISSUE TITLE
search in current playlist

### ISSUE THREAD

**Issue by ubermensh** [foobnix/foobnix#113]
I was not able to find this option, I think it is essential.

**Comment by zavlab1** [comment]
На то и табы в плейлистах сделаны, чтобы не нагружать плейлист так, что в нем еще и поиском надо пользоваться :). По альбому в каждую вкладку и будет счастье. А вот в музыкальной библиотеке поиск нужен, поэтому там и реализован.
Но если вдруг очень захотелось использовать сотни треков в одном плейлисте, то здесь надо использовать стандартный поиск Gtk+. Просто кликнуть на текущий плейлист и начать набирать искомую фразу.
