### ISSUE TITLE
Notification: I have added a foobnix package to the Arch User Repository (AUR)

### ISSUE THREAD

**Issue by fusion809** [foobnix/foobnix#114]
Hi,

I just thought I would create this issue to inform anyone that is interested that I have created a foobnix package in the Arch User Repository (AUR), which can be found [here](https://aur.archlinux.org/packages/foobnix/). I was quite surprised that no one had already done this, as packages already existed for most of the other popular distros, but any it is done now :). 

If you have yaourt installed on your Arch Linux machine, you can install foobnix now by running:
```bash
yaourt -S foobnix --noconfirm
```

Hope this helps,
Brenton

**Comment by zavlab1** [comment]
Thanks.
