### ISSUE TITLE
lost rpm package 

### ISSUE THREAD

**Issue by QIvan** [foobnix/foobnix#115]
Hi! I've tried install foobnix on Fedora 23 but [link with the rpm package](https://copr.fedorainfracloud.org/coprs/region51/foobnix/) is corrupted.

The command `dnf install foobnix` also has no result : 
```
Failed to synchronize cache for repo 'region51-flacon' from 'https://copr-be.cloud.fedoraproject.org/results/region51/flacon/fedora-23-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 0:24:23 ago on Sun Feb 21 21:17:32 2016.
No package foobnix available.
```

**Comment by lemenkov** [comment]
сс @region51

**Comment by region51** [comment]
Foobnix packages can be installed from russianfedora-free repo or directly from [koji](http://koji.russianfedora.pro/koji/packageinfo?packageID=20)

## Install repo:
`su -c 'dnf install --nogpgcheck http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/russianfedora-free-release-stable.noarch.rpm http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/russianfedora-nonfree-release-stable.noarch.rpm'`

## Install foobnix:
`dnf install foobnix`

**Comment by region51** [comment]
PS. off topic ^^^
```
Failed to synchronize cache for repo 'region51-flacon' from 'https://copr-be.cloud.fedoraproject.org/results/region51/flacon/fedora-23-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 0:24:23 ago on Sun Feb 21 21:17:32 2016.
No package foobnix available.
```
flacon http://flacon.github.io/download/

**Comment by QIvan** [comment]
Thank you! Can you refresh info on your [site](http://foobnix.com/en/download.html)? 

P.S. About off topic: that was default settings for `dnf` on Fedora 23 I don't know why `dnf` try to search foobnix in flacon repo. 
P.P.S I know about flacon progect I've even made one [pull-request](https://github.com/flacon/flacon/pull/11) for this one =)

**Comment by QIvan** [comment]
а, блин, можно было не выё***ся с английским, я думал у вас все таски на английском ведутся... Извиняйте, ребят, ещё раз спасибо за помощь =)

**Comment by region51** [comment]
>Thank you! Can you refresh info on your site?

ну это вопрос не ко мне, а @foobnix @zavlab1

**Comment by zavlab1** [comment]
На сайте разместил, хотя насчет этого:
`Failed to synchronize cache for repo 'region51-flacon' from 'https://copr-be.cloud.fedoraproject.org/results/region51/flacon/fedora-23-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 0:24:23 ago on Sun Feb 21 21:17:32 2016.
No package foobnix available.`
я ничего не понял.

**Comment by QIvan** [comment]
ну просто если накатить свежую федору и запустить команду `dnf install foobnix` будет вывод именно такой.

**Comment by region51** [comment]
@QIvan привет, а ты установил foobnix?
PS. Если что, то я могу сделать пакет с последними исправлениями.

**Comment by QIvan** [comment]
да, установил. 
Пакет с последними правками был бы не лишним - это точно )

**Comment by region51** [comment]
@QIvan 
>Пакет с последними правками был бы не лишним - это точно )

Держи http://koji.russianfedora.pro/koji/taskinfo?taskID=66190 
или можно обновить так
`sudo dnf update http://koji.russianfedora.pro/kojifiles/work/tasks/6190/66190/foobnix-3.1.2-3.20160224gita1d7246.fc23.R.noarch.rpm`

**Comment by region51** [comment]
@QIvan ping?

**Comment by QIvan** [comment]
упс, почему-то пропустил последнее сообщение.
обновился, теперь падает стабильно =) 
$ foobnix 
/usr/bin/xclip
start program
Segmentation fault (core dumped)

с флагом debug нужен вывод?

**Comment by region51** [comment]
@zavlab1 @QIvan добро пожаловать соседнюю тему https://github.com/foobnix/foobnix/issues/120

**Comment by region51** [comment]
@QIvan если есть желание выявить проблему, то можешь продолжить то, что я там начал
gdb python
run /usr/bin/foobnix

просто у меня нет, скажем так желания ставить все Missing separate debuginfos ... в 300мб

**Comment by zavlab1** [comment]
Да просто хотя бы запусти 
foobnix --debug

P.S.: А насчет gdb - думаю, не проблема на несколько дней 300Мб установить.

**Comment by QIvan** [comment]
ну я ковырялся с дебагером в исходниках, но при запуске с чистого питона (без make) у меня нормально работает, так что хз что там. 
Ну и прога где-то раза с 3-4 запускается =)

**Comment by zavlab1** [comment]
А вот это интересно. Получается, если запускать версию из исходников, то работает нормально, а если из пакета, то крэшится? Я правильно понял?
Кто-нибудь пробовал вообще ставить из git (предварительно конечно установив пакет - для удовлетворения зависимостей).
Например, так:
```
git clone https://github.com/zavlab1/foobnix.git
cd ~/foobnix git pull
cd ~/foobnix/src python foobnix.py
cd ~/foobnix/src python foobnix.py --debug
```
И вообще, я от кого-нибудь увижу вывод из консоли foobnix --debug   :)

**Comment by region51** [comment]
>А вот это интересно. Получается, если запускать версию из исходников, то работает нормально, а если из пакета, то крэшится? Я правильно понял?

не знаю как у @QIvan, но  у меня не имеет значения, так или так падает одинаково.
