### ISSUE TITLE
Missing translation and tooltip 

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#116]
Fedora 23, foobnix-3.1.2 last git commit.
В общем нет перевода.
![2016-02-22 16-33-15](https://cloud.githubusercontent.com/assets/13280183/13219606/36d7a68a-d982-11e5-89ca-726d0cfc699f.png)
![2016-02-22 16-33-24](https://cloud.githubusercontent.com/assets/13280183/13219610/3b9cfdfa-d982-11e5-85f6-0c8cccf105d7.png)

**Comment by region51** [comment]
PS. Также нет перевода "Choose" и "Delete"
![2016-02-22 17-03-39](https://cloud.githubusercontent.com/assets/13280183/13220288/65cc6116-d986-11e5-9dcb-5e921379bba3.png)

**Comment by zavlab1** [comment]
Вроде поправил. Тестируйте

**Comment by region51** [comment]
Первое исправлено.
Второе нет.

**Comment by region51** [comment]
@zavlab1 а "Choose" и "Delete" поправишь???

**Comment by zavlab1** [comment]
Уже. Просто переводы на launchpad могут несколько дней обновляться.
