### ISSUE TITLE
Broken add files

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#117]
Fedora 23, foobnix-3.1.2 last git commit.
В общем тупо нет никакой реакции на Файл - Добавить файл(ы)
![2016-02-22-164227_1280x1024_scrot](https://cloud.githubusercontent.com/assets/13280183/13219828/8d04c456-d983-11e5-92d8-183ae85b4ab2.png)
также на непереведённый +Add Folder(s) in tree
![2016-02-22 16-48-43](https://cloud.githubusercontent.com/assets/13280183/13219941/2f46fa54-d984-11e5-9584-75e4c15058da.png)
то есть выбираю и ничего.

**Comment by region51** [comment]
PS. Также нет реакции на Помощь - Сведения о программе

**Comment by region51** [comment]
>PS. Также нет реакции на Помощь - Сведения о программе

Исправлено.

>также на непереведённый +Add Folder(s) in tree

Переведен, но все также не работает

**Comment by zavlab1** [comment]
Очень странно. После моих правок у меня все отлично работает. Удалил проект, вытянул заново с Github и снова все работает. Может выхлоп какой терминал дает?

**Comment by region51** [comment]
@zavlab1 через меню Файл - Добавить файл(ы) работает, через +Add Folder(s) in tree нет.
>Может выхлоп какой терминал дает?

про выхлоп в соседней теме https://github.com/foobnix/foobnix/issues/120

**Comment by region51** [comment]
еще раз проверил + Добавить папку(и) в дерево не работает, то есть появляется диалог, где выбираем и ничего не происходит.

**Comment by zavlab1** [comment]
>  то есть появляется диалог, где выбираем и ничего не происходит.
Вот это уже что-то. А то я думал, что диалог не появляется. Тут будем посмотреть.

**Comment by region51** [comment]
@zavlab1 дык, я ведь сразу привел скрин с этим диалогом "+Add Folder(s) in tree" где написал "то есть выбираю и ничего."

**Comment by zavlab1** [comment]
Видимо я невнимателен был. Сейчас поправил. Тестируем

**Comment by region51** [comment]
@zavlab1 так, теперь добавляет, но теперь ... это так должно быть после того как добавил, то есть пропадает + Добавить папку(и) в дерево
![2016-02-23 18-04-04](https://cloud.githubusercontent.com/assets/13280183/13255709/57034adc-da58-11e5-885f-d51527b46afb.png)

**Comment by region51** [comment]
@zavlab1 еще кое-что заметил, иногда происходит такое с Расш
![2016-02-23 18-04-07](https://cloud.githubusercontent.com/assets/13280183/13255846/26c7fd1c-da59-11e5-971d-76f92ca9f285.png)
а должно быть всегда так
![2016-02-23 18-11-47](https://cloud.githubusercontent.com/assets/13280183/13255854/30cd1d24-da59-11e5-953a-4cdf3e19da76.png)

**Comment by zavlab1** [comment]
Да, так должно быть.

**Comment by zavlab1** [comment]
Насчет Расш - здесь думаю надо отдельный баг заводить и следить, когда и в каком случае проявляется баг, чтобы я мог воспроизвести. Потому как в моем плеере все нормально.

**Comment by region51** [comment]
@zavlab1 
>Да, так должно быть.

но как тогда это понимать
![2016-02-23 18-27-05](https://cloud.githubusercontent.com/assets/13280183/13256296/219c0ee4-da5b-11e5-9033-801685178283.png)

**Comment by zavlab1** [comment]
Такого не должно быть. Помоги воспроизвести.

**Comment by region51** [comment]
@zavlab1 да все просто открыл/закрыл то так, то ни так.

**Comment by region51** [comment]
@zavlab1 открой + Добавить папку(и) в дерево она пропадет, далее открой Пустую вкладку и она появится снова.
