### ISSUE TITLE
Convert FLAC to MP3

### ISSUE THREAD

**Issue by mapomme1108** [foobnix/foobnix#124]
Hello,

I have installed Foobnix on a Debian Jessie.

I would like to know if it is possible to convert FLAC files to MP3 files using command line.
Because I want to automate the process.

Thanks per advance for your help.

**Comment by zavlab1** [comment]
Hello.
Yes of cause. But interface foobnix supports batch convert flac2mp3. Our converter is gui for ffmpeg.
Select flac files. Pight click on selection. Choose Format Converter...

Why do you need to automate the process if it has long been automated?

**Comment by mapomme1108** [comment]
Hello,

I need to do it on a Debian server by command line
I found and use Pearl Audio Converter now and it works.

**Comment by zavlab1** [comment]
Excellent. May I to close issue?

**Comment by mapomme1108** [comment]
Yes, you can close the issue.
