### ISSUE TITLE
strip is black

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#126]
_-Foobnix version: 3.1.2 fda06da2902e53869c36fa06631cb430d8201dcd_
![screenshot from 2016-04-25 17-43-49](https://cloud.githubusercontent.com/assets/13280183/14787767/99e15642-0b0d-11e6-829c-17f1093aa84d.png)
Когда хочешь закрыть табы, то появляется черная полоса рядом.
Это так задуманно???

**Comment by zavlab1** [comment]
Да.
