### ISSUE TITLE
Feature Request: Symbolic icons

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#128]
Было бы неплохо иметь данную иконку.

**Comment by zavlab1** [comment]
Каждая система подбирает иконки из своего набора. Новая kde почти полностью перешла на символические иконки. Gnome тоже, но кажется в меньшей степени. Я кстати вчера поменял кое-где иконки и был рад увидеть, что в Федоре они стали символическими. Еще не коммитил, но скоро выложу.

**Comment by region51** [comment]
@zavlab1 ты не правильно меня понял, это одна иконка в

_/usr/share/icons/hicolor/*/apps/foobnix-symbolic.svg_

Пример
![screenshot from 2016-04-26 21-22-47](https://cloud.githubusercontent.com/assets/13280183/14829713/81ff6594-0bf5-11e6-8748-264033221d45.png)
symbolic
![screenshot from 2016-04-26 21-22-37](https://cloud.githubusercontent.com/assets/13280183/14829721/8cc2fcf2-0bf5-11e6-8af7-b573030db3a1.png)

**Comment by region51** [comment]
Как бы все нормальные приложения уже сделали свою иконку, присоединяйся, так как эти мелочи только к лучшему.

**Comment by zavlab1** [comment]
Так я тогда не пойму, какое отличие такой иконки от обычной? SVG формат?

**Comment by region51** [comment]
@zavlab1 в Gnome по умолчанию, если нет этой иконки запускается родная, если есть symbolic она в приоритете. Это стандарт.

**Comment by region51** [comment]
P.S. А отличие единый стиль.

**Comment by zavlab1** [comment]
Тут тогда другая пробема возникает. В Gnome есть светлые темы и темные. Если я делаю иконку серым на прозрачном фоне - тогда в темной не видно. Если белой на прозрачном - тогда не видно в светлой. Как получить универсальную? Или может у Гнома есть правила, когда какую загружать?

**Comment by region51** [comment]
>Тут тогда другая пробема возникает. В Gnome есть светлые темы и темные.

Какая блин проблема, в GNOME темная тема это дефолт.

**Comment by region51** [comment]
@zavlab1 Ну или так, сделай иконку и положи ее рядом, чтобы майнтейнер сам по своему желанию выбирал устанавливать ее или нет.

**Comment by region51** [comment]
mpv https://github.com/mpv-player/mpv/blob/master/etc/mpv-symbolic.svg
gnome-mpv https://github.com/gnome-mpv/gnome-mpv/blob/master/data/gnome-mpv-symbolic.svg
lollypop https://github.com/gnumdk/lollypop/blob/master/data/icons/hicolor/scalable/apps/lollypop-symbolic.svg

**Comment by region51** [comment]
@zavlab1 так что, будет чудесная иконка или нет?

**Comment by zavlab1** [comment]
Ну так сделал вроде. Иконки переведены в svg. Для цветных сделаны symbolic версии.
Кода для использования векторных иконок много переделать пришлось, так что тестируй хорошо все, что связано с иконками.

**Comment by region51** [comment]
@zavlab1 привет, видимо ты все-таки не понял, нужна это одна иконка в

/usr/share/icons/hicolor/*/apps/foobnix-symbolic.svg

примеры https://github.com/foobnix/foobnix/issues/128#issuecomment-215010666

**Comment by zavlab1** [comment]
Ты думаешь ее нет?

**Comment by region51** [comment]
ну я ее не вижу
где?

**Comment by region51** [comment]
@zavlab1 ааа, стоп, я смотрю эту репу, я все забываю что у тебя своя.

**Comment by region51** [comment]
@zavlab1 ага, вот она https://github.com/zavlab1/foobnix/blob/17c6b5fbe16b65d3109d5cf757ada7424d39d126/share/foobnix/images/hicolor/scalable/apps/foobnix-symbolic.svg

надо проверить

**Comment by region51** [comment]
@zavlab1 

надо положить так
/usr/share/icons/hicolor/scalable/apps/foobnix.svg
/usr/share/icons/hicolor/symbolic/apps/foobnix-symbolic.svg

а не все в одну
/share/foobnix/images/hicolor/scalable/apps

**Comment by region51** [comment]
>так что тестируй хорошо все, что связано с иконками.

ну лично позаимствовал 2 иконки

_foobnix.svg_
_foobnix-symbolic.svg_

которые будут в 

_/usr/share/icons/hicolor/scalable/apps/foobnix.svg_
_/usr/share/icons/hicolor/symbolic/apps/foobnix-symbolic.svg_

**Comment by region51** [comment]
@zavlab1 что-то не то
![screenshot from 2016-05-11 16-16-23](https://cloud.githubusercontent.com/assets/13280183/15182282/5983790c-1794-11e6-827a-3af4748108ed.png)

**Comment by zavlab1** [comment]
Итак.
По первому вопросу. Куда класть иконки.
Действовал в соответствии с документацией Gnome с использованием GtkIconTheme API (в отличие от многих других приложений, которые как раз и пихают иконки в общие папки).
https://developer.gnome.org/ThemedIcons/
Там сказано, что если приложение использует собственные иконки, то директорию с этими иконками надо добавить в search path текущей темы гнома. Обычно это директория ${pkgdatadir}/icons/hicolor, где ${pkgdatadir} это каталог с данными приложения - в нашем случае /usr/share/foobnix
Итак, я добавляю папку с иконками в гномотемовский путь поиска:
Gtk.IconTheme.get_default().append_search_path(/usr/share/foobnix/icons/hicolor/images)

Теперь мои иконки доступны без указания пути. При совпадении имени иконки с системной - будет грузиться системная. Если же в системе нужной иконки нет, будет грузиться моя. Очень удобно.

По второму вопросу. Белый квадрат вместо иконки.
Тут могу только предполагать. Сейчас переделал иконки. Попробуй обновись. Плюс возможно у тебя мешаются старые иконки от предыдущих установок из пакета.

**Comment by region51** [comment]
>Плюс возможно у тебя мешаются старые иконки от предыдущих установок из пакета.

исключено.

**Comment by region51** [comment]
@zavlab1 тоже самое

**Comment by region51** [comment]
@zavlab1 symbolic должна быть сквозная, прозрачная

**Comment by zavlab1** [comment]
Думаю, дело в реализации иконок. Там много подводных камней, которые нигде не описаны (я не нашел) и приходится продвигаться наощупь через Inkscape. Сейчас сделал новую версию иконки. Пробуй.

**Comment by zavlab1** [comment]
Да, прозрачную сделал.

**Comment by region51** [comment]
>Да, прозрачную сделал.

нет

**Comment by zavlab1** [comment]
в том коммите, что я пять минут назад забадяжил, должна быть прозрачная

**Comment by region51** [comment]
>в том коммите, что я пять минут назад забадяжил, должна быть прозрачная

да, вот это то что надо, чуть попожже покажу скрин

**Comment by zavlab1** [comment]
Другие иконки тоже сделал прозрачными. Обновись.
