### ISSUE TITLE
Call python 2 function in setup.py

### ISSUE THREAD

**Issue by marillat** [foobnix/foobnix#142]
Line 48 file() should be replaced by open()

**Comment by foobnix** [comment]
yes, this is not only one issue, we need to fix setup.py

**Comment by marillat** [comment]
See https://github.com/foobnix/foobnix/pull/143

**Comment by foobnix** [comment]
done, but if you run insalled foobnix it's not works, need more fix to seput.py

foobnix 
Traceback (most recent call last):
  File "/usr/local/bin/foobnix", line 16, in <module>
    from foobnix.fc.fc import FC
ModuleNotFoundError: No module named 'foobnix'

**Comment by marillat** [comment]
Well a file installed in /usr/local should not call setup.py at all.

**Comment by foobnix** [comment]
it's not call setup.py, please fix setup.py if you can

**Comment by marillat** [comment]
Maybe python file aren't installed in the right place ?

**Comment by marillat** [comment]
May be you need to add /usr to load path ?

```
--- a/foobnix/gui/service/path_service.py
+++ b/foobnix/gui/service/path_service.py
@@ -19,6 +19,7 @@ def get_foobnix_resourse_path_by_name(fi
              "share/pixmaps",
              "share/foobnix",
              "share/pixmaps",
+             "/usr",
              "./",
              filename]
```

**Comment by marillat** [comment]
Package for debian unstable is here (maybe some python dependencies are missing)

https://www.deb-multimedia.org/tests/foobnix_3.2-dmo1_all.deb
