### ISSUE TITLE
Foobnix PPA is down...

### ISSUE THREAD

**Issue by epicstar** [foobnix/foobnix#67]
BTW, I'm using Linux Mint 17.1. I went to your [download](http://www.foobnix.com/en/download.html) site to download foobnix but when adding your ppa:foobnix-team/foobnix-player, I get 404 errors on apt-get update. In the meantime, I installed the unstable version.

**Comment by zavlab1** [comment]
Привет, я же тебе в прошлом письме писал, что 2.6.10 уже не поддерживаем, 
пускай ставит 3.0. Можно вообще про 2.6.10 с сайта убирать инфу. Или оставить 
только как версию под винду и старые дистры. А основная 3.0, но у нас она 
собрана только под дебориентированные дистры, как под другие собирать я без 
понятия.


В письме от 21 января 2015 08:56:32 пользователь Jeremy Jao написал:
> BTW, I'm using Linux Mint 17.1. I went to your
> [download](http://www.foobnix.com/en/download.html) site to download
> foobnix but when adding your ppa:foobnix-team/foobnix-player, I get 404
> errors on apt-get update. In the meantime, I installed the unstable
> version.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/foobnix/foobnix/issues/67

-- 
С уважением,
Дмитрий

**Comment by sojusnik** [comment]
> А основная 3.0, но у нас она собрана только под дебориентированные дистры, как под другие собирать я без понятия.

А где именно можно скачать актуальную и работающую версию вашего плеера под Ubuntu 14.10?

**Comment by zavlab1** [comment]
В письме от 11 февраля 2015 00:32:22 пользователь sojusnik написал:
> А основная 3.0, но у нас она собрана только под дебориентированные дистры,
> как под другие собирать я без понятия.
> 
> А где именно можно скачать актуальную и работающую версию вашего плеера под
> Ubuntu 14.10?

В виде дебки пока нигде, т.к. куда-то пропал наш майнтейнер. Уже давно пытаюсь 
с ним связаться. Видимо, придется самому сборкой заняться, просто пока 
некогда, на работе завал. Там еще надо будет переводы поправить. Правда, если 
буду собирать я, то 3-я версия попадет в наш старый репозиторий.

**Comment by sojusnik** [comment]
Спасибо, Дмитрий!

**Comment by zavlab1** [comment]
Да не за что. Кстати, если нетерпится, то версия для trusty должа полностью подходить под utopic.

**Comment by sojusnik** [comment]
Поставил - работает!

Особенно нравиться интеграция Вконтакте и Last.fm. Плеер очень мощный, но есть над чем поработать.

Если нужна помощь с переводом на немецкий и английский, то обращайтесь!
