### ISSUE TITLE
How to add file to current playlist?

### ISSUE THREAD

**Issue by d9k** [foobnix/foobnix#68]
Foobnix 2.6.10.
How to add file to current playlist without drag-n-drop from openned file manager?
When I do `File->Add File(s)...` new files are added to NEW playlist named as files folder (even if playlist with such name already exists) but not to the current openned playlist.

**Comment by zavlab1** [comment]
Simlest way is just to install foobnix 3 instead 2.6.10. There is realized needed behavior (File-Add files(s) appends in current playlist). Double click in file manager too.
For 2.6.10 you need firstly add files or folders to Music Library tree and then add in current playlist by drag-and-drop from Music Library.

**Comment by d9k** [comment]
Thanks! foobnix 3 works great.
At first I installed it from sources but I couldn't resolve dependancies (For example `ImportError: cannot import name Notify`. I have Kubuntu 14.04). Then I tried ppa `sudo add-apt-repository ppa: popsul1993/ppa; ...` and foobnix ran perfectly.

**Comment by zavlab1** [comment]
Version Foobnix 3 in ppa is rather old. It does not work lyrics and it have some problems with vk-service. Therefore, I advise to run from source (after you have installed the package all the dependencies are already satisfied). In the source code (my branch - zavlab1/gtk3) all of the above problems have been fixed.
