### ISSUE TITLE
Частое падение

### ISSUE THREAD

**Issue by sojusnik** [foobnix/foobnix#73]
Foobnix 3 к сожалению часто падает под Ubuntu Gnome 14.10.

Как лучше всего найти причину? Может где-то есть log файлы или тому подобное?

**Comment by zavlab1** [comment]
Странно. У меня уже пару лет не было висов и падений. Но у меня KDE.
Как отловить причину? Посмотрите сюда https://github.com/foobnix/foobnix/wiki/How-to-catch-bug-and-make-bugreport-%28russian%29
Ну а самую подробную инфу найдете в первом сообщении темы под спойлером здесь - http://forum.ubuntu.ru/index.php?topic=201253.0

**Comment by sojusnik** [comment]
Спасибо!
