### ISSUE TITLE
Главное окно не реагирует

### ISSUE THREAD

**Issue by sojusnik** [foobnix/foobnix#75]
При переключении с одной программы на Foobnix, главное окно, ни с того ни с сего, стало больше не реагировать, но музыка на заднем фоне продолжает играть, даже проигрываются следующие треки.

Окно скорее всего зависло во время песни Dance Of The Wildflowers.

[foobnix_log.txt](https://mega.co.nz/#!G5hkUYbb!obHL10T_1Gd0vabtUeNSLJiO9qhC6chEydjIS_USzPo)

Foobnix 3.0.02 на Ubuntu Gnome 14.10.

Спасибо!

**Comment by sojusnik** [comment]
... и еще одни [log](https://mega.co.nz/#!e1I0hDJK!4syaDYxWzIew54oQnXZ-mbkR_jnk7TwS47TJypFIHfQ).

**Comment by POPSuL** [comment]
@sojusnik логи лучше выкладывать либо тут, либо на pastebin.com/dumpz.org. Ибо на том ресурсе их невозможно прочесть без скачивания.

**Comment by sojusnik** [comment]
Предыдущие вы можете сами скачать или мне их заново здесь выставить?

**Comment by zavlab1** [comment]
Можем скачать. Все нормально. Это на будущее.

**Comment by zavlab1** [comment]
Попытался решить проблему. Закоммитил решение в свою ветку. Переключался между интернет-композициями с бешеной скоростью, ничего не зависло и не упало. Попробуйте выкачать мою ветку и потестировать. 
cd ~
git clone https://github.com/zavlab1/foobnix.git
cd ~/foobnix
git pull
python ~/foobnix/foobnix.py

Надеюсь, Вам поможет. Если так, то соберу пакеты.

**Comment by sojusnik** [comment]
Вроде работает, можно соберать пакеты. Спасибо!
