### ISSUE TITLE
Use Github Releases

### ISSUE THREAD

**Issue by pradyun** [foobnix/foobnix#79]
I have a small suggestion/request.

Please use the [Github releases](https://github.com/blog/1547-release-your-software) infrastructure to make releases. It makes it possible to remove the dependency from code.google.com as well as keep the downloads with the repository.

While making it easier for us, users to get hold of the binaries, it also allows you to use simple git tags to make releases.

**Comment by lemenkov** [comment]
Related #44

**Comment by zavlab1** [comment]
Done.
https://github.com/foobnix/foobnix/releases/tag/3.0

**Comment by pradyun** [comment]
:+1:

**Comment by POPSuL** [comment]
:beer: :+1:
