### ISSUE TITLE
Error in foobnix after installed.

### ISSUE THREAD

**Issue by namoplasta** [foobnix/foobnix#85]
$foobnix
/usr/bin/xsel
start program
[ERROR   ] [05:53:26] [fc_helper.py:89] Error load configpickle data was truncated
[ERROR   ] [05:53:26] [importer.py:51] Could not find any typelib for Keybinder
('******Foobnix run in', 1.7839090824127197, ' seconds******')

The foobnix apear but is frozen. 

I tried to install the .deb and source code, both give the same error, I am using debian wheezy.

**Comment by zavlab1** [comment]
Try to install this package https://packages.debian.org/jessie/gir1.2-keybinder-3.0 and tell my about result.

**Comment by namoplasta** [comment]
gir1.2-keybinder-3.0 has been installed, but now this:
$ foobnix
/usr/bin/xsel
start program
[ERROR   ] [06:23:31] [fc_helper.py:89] Error load configpickle data was truncated
('******Foobnix run in', 2.1580889225006104, ' seconds******')

Foobnix is frozen.

**Comment by zavlab1** [comment]
Remove ~/.config/foobnix3 folder. Run foobnix in terminal with --debug option and attach output to your comment.

**Comment by namoplasta** [comment]
http://pastebin.com/raw.php?i=pNvuncdz

**Comment by zavlab1** [comment]
I can not reproduce this. I have tried catch this bug on ubuntu, kubuntu, debian wheezy and jessie, but player work excellently.
