### ISSUE TITLE
Defining Keyboard Shortcuts for playing/pausing/next

### ISSUE THREAD

**Issue by shivams** [foobnix/foobnix#86]
This is a feature request. 

There should be global keyboard shortcuts for playing, pausing or going to the next/previous track. And these should be customizable. 

Alternatively, you could provide some commands so that we could do these things right from the terminal. These commands could be set for the preferred key combinations in the "Keyboard Shortcuts" of the X system by the user.

**Comment by zavlab1** [comment]
Parameters - Hotkeys do not suit you? Why?

**Comment by shivams** [comment]
@zavlab1 : I am not aware of the hotkeys. How do we set them? They aren't there in the GUI. 

Anyways, I found out in the man page that commands are available to control your foobnix. E.g. to play next song, I mapped this command to my keyboard's "play next media" key: 

    foobnix --next

**Comment by zavlab1** [comment]
In Preferences is item "Hotkeys" with GUI
![vm1](https://cloud.githubusercontent.com/assets/432591/7291899/e152f1e8-e99e-11e4-9ae2-e98d103942d3.jpg)

**Comment by shivams** [comment]
The option is not there in my foobnix. It's surprising. My version is also 3.0.04. How is this possible? FYI, I am on Linux Minu17.1 and installed it via the PPA.

**Comment by zavlab1** [comment]
Is there installed gir1.2-keybinder-3.0 package on your system?

**Comment by shivams** [comment]
@zavlab1 : That's it. I installed that package and the option is showing up now.

The issue is resolved. Thanks a lot for your swift responses :)

**Comment by zavlab1** [comment]
Tell me please, what application you used for installing the package?
The package gir1.2-keybinder-3.0 is recommended dependence and apt installs it automatically, but gdebi (for example) is not.

**Comment by shivams** [comment]
I installed foobnix a few months back, so I don't remember exactly which method I used : apt or setup.py. Most probably I used apt. 

But gir1.2-keybiner-3.0 was definitely not installed. I installed it manually later after your answer here.
