### ISSUE TITLE
Отображается криво.

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#87]
@zavlab1 @foobnix *Fedora 21/22* и *Foobnix 3.0.4* смотрите на косяк в левой панели. Надо самому двигать панель и скажу я вам, что её не так-то просто расширить, т.к она не понятно как закрепляется. Проясните ситуацию.
![2015-05-30 12 25 46](https://cloud.githubusercontent.com/assets/11947263/7896637/1e1a2bb4-06c8-11e5-8b25-fd990174b2e6.png)
![2015-05-30 12 26 02](https://cloud.githubusercontent.com/assets/11947263/7896638/22852a8c-06c8-11e5-88f1-df62a7104ddd.png)
![2015-05-30 12 26 16](https://cloud.githubusercontent.com/assets/11947263/7896639/27a8e2d8-06c8-11e5-88d9-1804ee9ccbb7.png)

**Comment by zavlab1** [comment]
Здравствуйте. Действительно в последних версиях популярных осей (Ubuntu 15.04, Debian 8 и Fedora 22) появился данный глюк. Видимо, обновились какие-то либы. У меня на LTS версии такого безобразия нет. Надо будет при случае разобраться с этим, а то действительно пользоваться проблематично.
Кстати, а как Вы на Fedora устанавливали? Есть готовый rpm?

**Comment by region51** [comment]
Ну что же теперь понятно. Решай проблему, а то люди ставят и плюются, а плеер то отличный.
>Кстати, а как Вы на Fedora устанавливали? Есть готовый rpm?

Вот когда исправишь, то можно и .rpm сделать, а пока так `sudo python setup.py install`

**Comment by region51** [comment]
@zavlab1 привет, ну как там процесс идет? 
>Есть готовый rpm?

уже есть
```
[maxim@localhost ~]$ yum info foobnix
Установленные пакеты
Название: foobnix
Архитектура: x86_64
Версия: 3.0.04
Выпуск: 1.fc21.R
Объем: 3.8 M
Источник: installed
Из источника: /foobnix-3.0.04-1.fc21.R.x86_64
Аннотация: Simple and Powerful music player for Linux
Ссылка: http://foobnix.com
Лицензия: GPLv3
Описание: Main player features:
        :  * Supports CUE (also wv, iso.wv), this is the best under Linux;
        :  * Multiple formats available, including MP3, MP4, AAC, CD Audio,
        :    WMA, Vorbis, FLAC, WavPack, WAV, AIFF, Musepack, Speex, AU, SND ...;
        :  * Foobnix supports cross-format exporting for MP3, OGG, MP2, AC3, M4A and WAV;
        :  * Scrobbler tags with music and radio available;
        :  * Find and play music and videos;
        :  * Equalizer;
        :  * Online music download manager;
        :  * Shortcuts;
        :  * Foobnix is able to display the album cover, lyrics, and artist photo;
        :  * VKontakte integration (displays all the friends and their music, able to download music from VKontakte groups);
        :  * Last.FM integration (shows and plays the best songs, favorite songs, and artists);

```

**Comment by zavlab1** [comment]
Пока криво идет. В новой версии GTK один из элементов плеера перестал принимать событие "button-press-event". Из-за этого и появилась проблема. Надо придумывать "костыль". Так что в процессе...

**Comment by zavlab1** [comment]
Вроде пофиксил. Обновитесь и потестируйте. Если все нормально, то соберите новый пакет, если не сложно и пришлите мне.

**Comment by region51** [comment]
@zavlab1 
>Вроде пофиксил. Обновитесь и потестируйте

Это вечером, после работы.

>Если все нормально, то соберите новый пакет, если не сложно и пришлите мне.

не вопрос.

**Comment by region51** [comment]
@zavlab1 да, теперь всё нормально. Вечером пришлю.

**Comment by xlin** [comment]
@zavlab1 Где скачать исправленный тарболл? На ланчпаде исходники от 13.03.2015
@region51 Где src пакет? Не гоже его не публиковать.

**Comment by region51** [comment]
Где src пакет?

5 июня 2015 г., 18:40 пользователь Valentin B. Saikov <
notifications@github.com> написал:

**Comment by region51** [comment]
>Где src пакет?

добавил

**Comment by xlin** [comment]
@region51 Спасибо. Хочу твой spec сравнить со своим.

**Comment by region51** [comment]
@xlin а в mageia такая беда была?

**Comment by zavlab1** [comment]
> Где скачать исправленный тарболл?
https://github.com/foobnix/foobnix/archive/master.tar.gz

**Comment by xlin** [comment]
> а в mageia такая беда была?
Не знаю, но хочу обновить пакет. =)

**Comment by zavlab1** [comment]
@region51 RPM-пакеты видимо идентичны?
На сайте noarch выложу.

В ближайшее время запилю минорный релиз с этим исправлением - 3.1.00. Поэтому пропиши в rpm-пакет новый номер версии (3.1.00) плиз и я сразу выложу на launchpad в релизы (https://github.com/foobnix/foobnix/releases) дебку, rmp и tarboll.

**Comment by region51** [comment]
@zavlab1 сейчас сделаю.

**Comment by zavlab1** [comment]
Кстати, не знаете случаем, для Archlinux федоринские пакеты подойдут?

**Comment by region51** [comment]
@zavlab1 
 ни разу не Archlinux юзер, но увы нет и нет.

**Comment by zavlab1** [comment]
Вопрос. После установки на Fedora в Настройках (Preferences) есть ли пункт "Горячие клавиши" (Hotkeys)? А то жаловался тут один...

**Comment by region51** [comment]
@zavlab1 
>После установки на Fedora в Настройках (Preferences) есть ли пункт "Горячие клавиши" (Hotkeys)?

нет такого пункта, да и в репах `gir1.2-keybinder3.0` не имеется.

**Comment by xlin** [comment]
@zavlab1 В Mageia есть такой пункт

**Comment by xlin** [comment]
Нужны ли Вам пакетв для Mageia? Давно собранный и протестированный. Могу пересобрать с последней (минорной) версией

**Comment by region51** [comment]
@zavlab1 я разобрался, нужен пакет 
```
]$ yum info keybinder3
Установленные пакеты
Название: keybinder3
Архитектура: x86_64
Версия: 0.3.0
Выпуск: 4.fc21
Объем: 23 k
Источник: installed
Из источника: fedora
Аннотация: A library for registering global keyboard shortcuts
Ссылка: https://github.com/engla/keybinder/tree/keybinder-3.0
Лицензия: MIT
Описание: Keybinder is a library for registering global keyboard shortcuts.
        : Keybinder works with GTK-based applications using the X Window System.
        : 
        : The library contains:
        : - A C library, libkeybinder
        : - Gobject-Introspection bindings


```

**Comment by xlin** [comment]
Пакет для Mageia 5 http://packages.mageialinux.ru/mageia5/RPMS/noarch/foobnix-3.1.00-1.mga5.mrc.noarch.rpm
Пакет с исходниками и спек файлом для сборки http://packages.mageialinux.ru/mageia5/SRPMS/foobnix-3.1.00-1.mga5.mrc.src.rpm

**Comment by zavlab1** [comment]
> Нужны ли Вам пакетв для Mageia? Давно собранный и протестированный. Могу пересобрать с последней (минорной) версией.

Конечно. Не откажусь.

> прописал в зависимости, теперь есть такой пункт как "Клавиши быстрого доступа"

Ок. Спасибо. Жду новый пакет.
По аналогии можно проверить и другие пакеты из списка зависимостей. Если один из рекомендуемых например отсутствует, то соответсвенно пакету какая-либо функция может оказаться не рабочей.
Для дебок зависимости так выглядят:

Depends: ${python:Depends},${misc:Depends}, python-chardet, python-gi, python-simplejson, python-mutagen, gstreamer1.0-plugins-good, gir1.2-gstreamer-1.0, gir1.2-gst-plugins-base-1.0, gir1.2-gtk-3.0, gir1.2-webkit-3.0, gir1.2-soup-2.4, gir1.2-notify-0.7, gir1.2-soup-2.4, gettext

Recommends: python-setuptools, gir1.2-keybinder-3.0, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, gstreamer1.0-libav, gstreamer1.0-alsa, fuseiso, libmp3lame0, libfaac0

**Comment by zavlab1** [comment]
> Пакет для Mageia 5

@xlin Благодарю

**Comment by region51** [comment]
@zavlab1 
>Ок. Спасибо. Жду новый пакет.

а ничего, что там прописано в version.py 
>FOOBNIX_VERSION='3.0.04'

или я чего то недоронимаю

**Comment by xlin** [comment]
@region51
Что бы быть полностью уверенным в зависимостях, нужно пакеты собирать в чистом окпужении. В том же chroot или как делаю я - в docker контейнере с минимальной Mageia и внутри него разворачивается chroot.

**Comment by xlin** [comment]
@region51
Что бы быть полностью уверенным в зависимостях, нужно пакеты собирать в чистом окпужении. В том же chroot или как делаю я - в docker контейнере с минимальной Mageia и внутри него разворачивается chroot.

**Comment by xlin** [comment]
@region51
Что бы быть полностью уверенным в зависимостях, нужно пакеты собирать в чистом окпужении. В том же chroot или как делаю я - в docker контейнере с минимальной Mageia и внутри него разворачивается chroot.

**Comment by zavlab1** [comment]
@region51
Мой косяк, забыл закоммитить. Но это не страшно, т.к. номер в version.py используется для автоматической сборки deb и больше нигде. В принципе можешь и сам его поменять перед сборкой, если смущает.

**Comment by region51** [comment]
@zavlab1 
```
[maxim@localhost ~]$ rpm -q foobnix
foobnix-3.1.00-1.fc21.R.noarch
```
https://cloud.mail.ru/public/8Q6v/RJDm82nzK

**Comment by zavlab1** [comment]
Выпустил релиз! Всем спасибо! https://github.com/foobnix/foobnix/releases/tag/3.1

**Comment by region51** [comment]
@zavlab1 привет, т.к эта мелкая проблемка соответствует названию шапки, отпишусь здесь.
Смотри на столбец №, двойной формат не влазит ../..
![2015-06-19 15 45 47](https://cloud.githubusercontent.com/assets/11947263/8253836/2a4ab2f8-169c-11e5-999f-da6d0ea49d3e.png)
И для Fedora сделал https://copr.fedoraproject.org/coprs/region51/foobnix/
Надеюсь, через неделю-другую пересяду на F22, сделаю и для него пакет там же.
