### ISSUE TITLE
Gentoo: ImportError: No module named _bsddb

### ISSUE THREAD

**Issue by seamus-45** [foobnix/foobnix#91]
Привет. Этот модуль уже считается [устаревшим](https://docs.python.org/2/library/bsddb.html#module-bsddb) со времен Python-2.6.
В Gentoo все ебилды python >= 2.7.5-r2 с флагом berkdb замаскированы. Имеется ли возможность портировать на bsddb3?

**Comment by zavlab1** [comment]
Привет. Даже не знаю, о чем Вы. Т.к. программирую под Ubuntu, то понятия не имею, с какими флагами собраны его пакеты Python2.7. Знаю, что раньше Python притягивал зависимостью libdb5.1 (berkley5.1). Но в последних версиях Ubuntu такой зависимости нет. Соответственно не понимаю, какие действия от меня требуются по Вашему тикету.

**Comment by seamus-45** [comment]
На примере Ubuntu 14.04 trusty. Пакет libpython2.7-stdlib содержит в себе модуль bsddb. Ubuntu достаточно консервативна насчет обратных зависимостей. В Gentoo, в стандартной поставке Python такого модуля нет, т.к. он давно считается устаревшим. Его ручная установка не заурядная. Поэтому запустить Ваш плеер не представляется возможным. Трэйс:
```
... skip ...
  File "/usr/lib64/python2.7/site-packages/foobnix/util/id3_util.py", line 7, in <module>
    from _bsddb import api
ImportError: No module named _bsddb
```
P.S. Кажется я понял почему мы друг друга не поняли. Этот модуль импортируется в id3_util.py, но похоже нигде не используется. После небольшого патча плеер запустился:
```
--- id3_util.py.orig    2015-06-11 11:16:23.944464067 +0500
+++ id3_util.py 2015-06-11 11:16:32.870463868 +0500
@@ -4,7 +4,6 @@
 
 @author: ivan
 '''
-from _bsddb import api
 import os
 import logging
 import urllib
```
Я так понимаю нужно избавить foobnix от этой зависимости :)

**Comment by zavlab1** [comment]
OK. Даже не знаю, откуда там эта строка взялась. Может кто-то из соработников экспериментировал, а потом забыл убрать :)
Конечно избавлю от этой зависимости.

Просьба. Когда соберете пакет для gentoo, можете ссылочку кинуть? Добавим на сайт и в релизы https://github.com/foobnix/foobnix/releases

**Comment by seamus-45** [comment]
Обычно пакеты для Gentoo не собирают, а пишут ebuild (инструкции по сборке для установщика).  Я написал [ebuild](https://github.com/seamus-45/seamustuff/tree/master/media-sound/foobnix) для своего личного репозитория, но мой оверлей не официальный и в списках Gentoo не фигурирует.
Можно конечно разместить ebuild на сайте как есть, гентушники разберутся ))

**Comment by zavlab1** [comment]
Отлично. Разберутся, альтернативы для них все-равно нет :)

**Comment by zavlab1** [comment]
Поправил.
