### ISSUE TITLE
online music not works if token expired

### ISSUE THREAD

**Issue by foobnix** [foobnix/foobnix#93]
Music was added 2 days ago
Today it's not works
Token for song should renew it if expired
new search fix problem but it's not case

[DEBUG   ] [16:21:54] [dragdrop_tree.py:292] Plain append task: Other Options None
[DEBUG   ] [16:21:56] [base_controls.py:117] play current bean is  Kind of Zero feat Marvinok - Коломийки
[DEBUG   ] [16:21:56] [common_tree.py:333] Set play icon to bean
[DEBUG   ] [16:21:56] [vk_service.py:143] get_result(audio.get, owner_id=24854054&audio_ids=88927734, 0)
[DEBUG   ] [16:21:56] [vk_service.py:188] Try to get response from vkontakte
[DEBUG   ] [16:21:56] [vk_service.py:147] result {"error":{"error_code":201,"error_msg":"Access denied: Access to users audio is denied","request_params":[{"key":"oauth","value":"1"},{"key":"method","value":"audio.get"},{"key":"owner_id","value":"24854054"},{"key":"audio_ids","value":"88927734"},{"key":"auto_complete","value":"0"}]}}
[DEBUG   ] [16:21:56] [vk_service.py:156] error found!
[DEBUG   ] [16:21:56] [vk_service.py:114] do auth
[DEBUG   ] [16:21:56] [vk_service.py:132] idle task added, waiting...
[DEBUG   ] [16:21:56] [vk_service.py:120] trying to auth
[DEBUG   ] [16:21:56] [vk_service.py:75] waiting for answer...
[DEBUG   ] [16:21:57] [vk_service.py:78] answer found!
[DEBUG   ] [16:21:57] [vk_service.py:79] d9005da64cce119dd59cc6de22bf5ed7089b5dd3448698cee332be6c71d983a8aef6bb1f2e382e5035b4d
[DEBUG   ] [16:21:57] [vk_service.py:80] 6851750
[DEBUG   ] [16:21:57] [vk_service.py:130] task finished, result is ('d9005da64cce119dd59cc6de22bf5ed7089b5dd3448698cee332be6c71d983a8aef6bb1f2e382e5035b4d', '6851750')
[DEBUG   ] [16:21:57] [vk_service.py:135] auth result is True
[DEBUG   ] [16:21:58] [vk_service.py:143] get_result(audio.get, owner_id=24854054&audio_ids=88927734, 1)
[DEBUG   ] [16:21:58] [vk_service.py:188] Try to get response from vkontakte
[DEBUG   ] [16:21:58] [vk_service.py:147] result {"error":{"error_code":201,"error_msg":"Access denied: Access to users audio is denied","request_params":[{"key":"oauth","value":"1"},{"key":"method","value":"audio.get"},{"key":"owner_id","value":"24854054"},{"key":"audio_ids","value":"88927734"},{"key":"auto_complete","value":"0"}]}}
[DEBUG   ] [16:21:58] [vk_service.py:156] error found!
Unhandled exception in thread started by <bound method FoobnixCore._one_thread_play of <foobnix.gui.foobnix_core.FoobnixCore instance at 0x7f84f6ec5fc8>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/foobnix/gui/base_controls.py", line 395, in _one_thread_play
    self._play(bean)
  File "/usr/lib/python2.7/dist-packages/foobnix/gui/base_controls.py", line 409, in _play
    self.fill_bean_by_vk_aid(bean)
  File "/usr/lib/python2.7/dist-packages/foobnix/gui/base_controls.py", line 363, in fill_bean_by_vk_aid
    track = self.vk_service.find_track_by_id(bean.vk_audio_id)
  File "/usr/lib/python2.7/dist-packages/foobnix/gui/service/vk_service.py", line 286, in find_track_by_id
    line = result[1]
TypeError: 'NoneType' object has no attribute '__getitem__'
[DEBUG   ] [16:21:58] [lastfm_service.py:93] RUN INIT LAST.FM

**Comment by zavlab1** [comment]
Сейчас попробовал воспроизвести. Больше недели назад нашел музыку. Сегодня запустил. Жду несколько секунд и ссылка обновляется. Воспроизведение начинается. Поэтому непонятно, что фиксить. Все работает как надо...
