### ISSUE TITLE
foobnix 3.1: Отсутствует лейбл у "Multi tab mode" радио кнопки

### ISSUE THREAD

**Issue by seamus-45** [foobnix/foobnix#94]
![Скриншот](http://storage4.static.itmages.ru/i/15/0611/h_1434005911_7912505_941765e464.png)

**Comment by zavlab1** [comment]
Пофиксил. Плюс добавил 2 языка переводов и перенес "Размер буффера" в вкладку "Параметры сети". Закоммитил и залил в главную ветку. Можно пересобирать :)
