### ISSUE TITLE
Несколько "мелких проблем"

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#96]
Привет. Смотрим на столбец №, и видим, что двойной формат не влазит ../..
![2015-06-19 22 12 17](https://cloud.githubusercontent.com/assets/11947263/8261123/c9520b92-16d0-11e5-90a4-b3f98c402e8d.png)
Меня просто бесит, если дважды кликнуть по панели "№, Композиция, Время и ..." то трек перезапускается. **Зачем**??? По первому правоклику по данной панели сначало появляется ПКМ, и только со второго правоклика появляется
![2015-06-19 22 36 23](https://cloud.githubusercontent.com/assets/11947263/8261500/ce881266-16d3-11e5-905a-dab3db2ebde2.png)
по нормальной логике первый правоклик вообще лишний.
*Fedora 21, Foobnix 3.1.00 [https://copr.fedoraproject.org/coprs/region51/foobnix/](https://copr.fedoraproject.org/coprs/region51/foobnix/)*

**Comment by zavlab1** [comment]
Столбец расширю. Без проблем.
По второму - баг. Раньше по первому клику вылазило то что нужно. Надо разобраться, почему стало так.
За репы спасибо.

**Comment by region51** [comment]
@zavlab1 понятно.
>За репы спасибо.

Кстати, можешь обновить свои ссылки
https://copr.fedoraproject.org/coprs/region51/foobnix/
если нужны сами пакеты, то выдерни их отсюда, там 2 архитектуры
https://copr-be.cloud.fedoraproject.org/results/region51/foobnix/
Завтра я сотру этот коммент, т.к он не по теме.

**Comment by zavlab1** [comment]
Баги вроде устранил. 
Попробуйте, влезает ли у Вас сейчас Tracknumber в ширину колонки.

**Comment by zavlab1** [comment]
Но перед этим надо сбросить настройки в значение по умолчанию (в Preferences)

**Comment by region51** [comment]
Да теперь нормально, молодец и спасибо 
![2015-06-28 19-00-54](https://cloud.githubusercontent.com/assets/11947263/8397114/003bbf32-1dc9-11e5-8d17-0bd01a6b8e52.png)
и смотрю ты чуть поменял версию до 3.1.01
![2015-06-28 19-00-19](https://cloud.githubusercontent.com/assets/11947263/8397121/1e065a36-1dc9-11e5-8037-f1bb52527c2a.png)

Так как пересел на Fedora 22, то сделал пакеты с исправлениями по сегодняшний день
```
$ rpm -q foobnix
foobnix-3.1.01-1.fc22.noarch
```
https://copr.fedoraproject.org/coprs/region51/foobnix/
https://copr-be.cloud.fedoraproject.org/results/region51/foobnix/
