### ISSUE TITLE
rpmlint error

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#98]
Привет, исправь это 
```
$ rpmlint foobnix-3.1.01-1.fc22.noarch.rpm
foobnix.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/foobnix/thirdparty/sound_menu.py 644 /usr/bin/python
foobnix.noarch: E: non-executable-script /usr/lib/python2.7/site-packages/foobnix/preferences/preferences_window.py 644 /usr/bin/env
foobnix.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/foobnix/thirdparty/pylast.py
1 packages and 0 specfiles checked; 3 errors, 0 warnings.

```
*E: incorrect-fsf-address* смотрим http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt и меняем на
*Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA*.

*E: non-executable-script* ????????

**Comment by region51** [comment]
non-executable-script
>This text file contains a shebang or is located in a path dedicated for executables, but lacks the executable bits and cannot thus be executed. If the file is meant to be an executable script, add the executable bits, otherwise remove the shebang or move the file elsewhere.

**Comment by zavlab1** [comment]
Привет. Исправил. Пробуй пересобрать.

**Comment by region51** [comment]
Да теперь нормально
```
[maxim@ip200-235 noarch]$ rpmlint foobnix-3.1.01-1.fc22.noarch.rpm
1 packages and 0 specfiles checked; 0 errors, 0 warnings.


```
